version: '3.6'

services:
  
  sql:
    image: mysql:5.7
    container_name: sql
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=imse_sql_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 3306

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: imse_mongo_db
    expose:
      - 27017

  app:
    build: ./app
    container_name: app 
    restart: always
    ports: 
      - 5000:5000
