DROP TABLE IF EXISTS claim;
DROP TABLE IF EXISTS policy_options;
DROP TABLE IF EXISTS options;
DROP TABLE IF EXISTS policy;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS agent;
DROP TABLE IF EXISTS user